before:
  hooks:
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - 386
  binary: kubecredcache
archives:
- replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  draft: true
  github:
    owner: jamesdobson
    name: kubecredcache
brews:
  - name: kubecredcache
    github:
      owner: jamesdobson
      name: homebrew-kubecredcache
    url_template: "https://github.com/jamesdobson/kubecredcache/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: kubecredcache
      email: kubecredcache@softwarepunk.com
    folder: Formula
    homepage: "https://github.com/jamesdobson/kubecredcache"
    description: "kubecredcache makes kubectl run faster by caching the AWS EKS token"